### ISSUE TITLE
Site Role calculation incorrect

### ISSUE THREAD

**Issue by thechadd** [tableau/community-tableau-server-insights#17]
Howdy! Thanks so much for putting this on gitlab! On my version of the TS Users, I had to modify the Site Role calc to accurately identify the Viewer role:
```
IF [Admin Level_orig] = 10
    THEN 'Server Administrator'
ELSEIF [Site Role_orig] = 'Author'
    THEN 'Creator'
ELSEIF [Site Role_orig] = 'Publisher'
    THEN 'Explorer (can publish)'
ELSEIF [Site Role_orig] = 'Interactor'
    THEN 'Explorer'
ELSEIF [Site Role_orig] = 'BasicUser'
    THEN 'Viewer'
ELSEIF [Site Role_orig] = 'SiteAdministratorAuthor'
    THEN 'Site Administrator Creator'
ELSEIF [Site Role_orig] = 'SiteAdministrator'
    THEN 'Site Administrator Explorer'
ELSE [Site Role_orig]
END
```
There is no [Site Role_orig] of Viewer.
Here is the original
```
IF [Admin Level_orig] = 10
    THEN 'Server Administrator'
ELSEIF [Site Role_orig] = 'Author'
    THEN 'Creator'
ELSEIF [Site Role_orig] = 'Publisher'
    THEN 'Explorer (can publish)'
ELSEIF [Site Role_orig] = 'Interactor'
    THEN 'Explorer'
ELSEIF [Site Role_orig] = 'Viewer'
    THEN 'Viewer'
ELSEIF [Site Role_orig] = 'SiteAdministratorAuthor'
    THEN 'Site Administrator Creator'
ELSEIF [Site Role_orig] = 'SiteAdministrator'
    THEN 'Site Administrator Explorer'
ELSE [Site Role_orig]
END
```
I'd submit the fix, myself, but I am not good at git 😆

**Comment by mcoles** [comment]
Good timing, I'm updating them all for 2019.1 as we speak....thanks for submitting!

**Comment by thechadd** [comment]
@mcoles. Hey if you don't mind, can I attempt a branch and pull request with this change? This would be my first contribution to a gitlab project. Hopefully I could contribute more to this, too. No biggie either way. Cheers!

**Comment by mcoles** [comment]
@thechadd , absolutely. I just created a Development branch for you to submit your pull request to, since if you submit one based on Master, I have to merge it directly to it, or reject entirely, neither of which are good options. I have a feeling that Git is going to find a bunch of merge conflicts with different fixes people submit, though, because Tableau loves to make all kinds of edits in the XML for simple changes. This one should be okay, though, since you're just editing a calc.

**Comment by thechadd** [comment]
Alright, I give up. Spent all afternoon following tutorials, forking, cloning, and trying to stage and unstage line-by-line changes, and my software just isn't cooperating with my noobness. I'll leave it to you experts until I can spend more time to figure this out. Thanks again

**Comment by mcoles** [comment]
No problem @thechadd , I have had to learn as I go too, and am still doing so. :)
