### ISSUE TITLE
TS Data Sources not able to connect in Tableau Desktop

### ISSUE THREAD

**Issue by tspring12** [tableau/community-tableau-server-insights#22]
When trying to connect to the TS data sources previously built in this community I'm getting an escape error. I've made sure permissions were set up correctly and that the data sources were working before. Now I'm getting this error message: 
""
An error occurred while communicating with the data source.

The connection to the data source might have been lost.
ERROR: invalid regular expression: invalid escape \ sequence;
Error while executing the query
prepare.xml
DataServiceFailure
No details available.
<?xml version='1.0' encoding='utf-8' ?>

<sqlproxy>
  <logical-query version='1.2.0'>
    <selects>
      <field>[Calculation_1406811937370324993]</field>
      <field>[Calculation_698339484915068929]</field>
      <field>[Item Name (copy 2)]</field>
      <field>[TEMP(Calculation_906349491762446342)(2938853959)(0)]</field>
      <field>[TEMP(Calculation_906349491762446342)(3192199808)(0)]</field>
      <field>[TEMP(Calculation_979814406487343104)(3148463133)(0)]</field>
    </selects>
    <projectOp class='logical-operator'>
      <expressions>
        <binding name='[Calculation_1406811937370324993]'>
          <funcallExp class='logical-expression' function='$COLLATE_REMOTE$' shape='scalar'>
            <identifierExp class='logical-expression' identifier='[Calculation_1406811937370324993]' />
            <literalExp charset='0' class='logical-expression' collation='LROOT' datatype='string' value='&quot;LEN_RUS&quot;' />
          </funcallExp>
        </binding>
        <binding name='[Calculation_698339484915068929]'>
          <funcallExp class='logical-expression' function='$COLLATE_REMOTE$' shape='scalar'>
            <identifierExp class='logical-expression' identifier='[Calculation_698339484915068929]' />
            <literalExp charset='0' class='logical-expression' collation='LROOT' datatype='string' value='&quot;LEN_RUS&quot;' />
          </funcallExp>
        </binding>
        <binding name='[Item Name (copy 2)]'>
          <funcallExp class='logical-expression' function='$COLLATE_REMOTE$' shape='scalar'>
            <identifierExp class='logical-expression' identifier='[Item Name (copy 2)]' />
            <literalExp charset='0' class='logical-expression' collation='LROOT' datatype='string' value='&quot;LEN_RUS&quot;' />
          </funcallExp>
        </binding>
        <binding name='[TEMP(Calculation_906349491762446342)(2938853959)(0)]'>
          <funcallExp class='logical-expression' function='$COLLATE_REMOTE$' shape='scalar'>
            <identifierExp class='logical-expression' identifier='[TEMP(Calculation_906349491762446342)(2938853959)(0)]' />
            <literalExp charset='0' class='logical-expression' collation='LROOT' datatype='string' value='&quot;LEN_RUS&quot;' />
          </funcallExp>
        </binding>
        <binding name='[TEMP(Calculation_906349491762446342)(3192199808)(0)]'>
          <funcallExp class='logical-expression' function='$COLLATE_REMOTE$' shape='scalar'>
            <identifierExp class='logical-expression' identifier='[TEMP(Calculation_906349491762446342)(3192199808)(0)]' />
            <literalExp charset='0' class='logical-expression' collation='LROOT' datatype='string' value='&quot;LEN_RUS&quot;' />
          </funcallExp>
        </binding>
      </expressions>
      <aggregateOp class='logical-operator'>
        <measures>
          <binding name='[TEMP(Calculation_906349491762446342)(2938853959)(0)]'>
            <funcallExp class='logical-expression' function='MAX' shape='aggregate'>
              <identifierExp class='logical-expression' identifier='[name]' />
            </funcallExp>
          </binding>
          <binding name='[TEMP(Calculation_906349491762446342)(3192199808)(0)]'>
            <funcallExp class='logical-expression' function='MIN' shape='aggregate'>
              <identifierExp class='logical-expression' identifier='[name]' />
            </funcallExp>
          </binding>
          <binding name='[TEMP(Calculation_979814406487343104)(3148463133)(0)]'>
            <funcallExp class='logical-expression' function='SUM' shape='aggregate'>
              <literalExp class='logical-expression' datatype='integer' value='1' />
            </funcallExp>
          </binding>
        </measures>
        <groupbys>
          <binding name='[Calculation_1406811937370324993]'>
            <identifierExp class='logical-expression' identifier='[Calculation_1406811937370324993]' />
          </binding>
          <binding name='[Calculation_698339484915068929]'>
            <identifierExp class='logical-expression' identifier='[Calculation_698339484915068929]' />
          </binding>
          <binding name='[Item Name (copy 2)]'>
            <identifierExp class='logical-expression' identifier='[Item Name (copy 2)]' />
          </binding>
        </groupbys>
        <selectOp class='logical-operator'>
          <predicate>
            <funcallExp class='logical-expression' function='==' shape='scalar'>
              <identifierExp class='logical-expression' identifier='[name]' />
              <literalExp charset='0' class='logical-expression' collation='LEN_RUS' datatype='string' value='&quot;Access View&quot;' />
            </funcallExp>
          </predicate>
          <projectOp class='logical-operator'>
            <expressions>
              <binding name='[Calculation_1406811937370324993]'>
                <caseExp class='logical-expression'>
                  <literalExp class='logical-expression' datatype='boolean' value='true' />
                  <funcallExp class='logical-expression' function='REGEXP_MATCH' shape='scalar'>
                    <identifierExp class='logical-expression' identifier='[$temp0_cse]' />
                    <literalExp charset='0' class='logical-expression' collation='LEN_RUS' datatype='string' value='&quot;^(2. Budget and Forecast|3. Digital Media|4. Paid Search|5. Display &amp; Paid Social|6. Affiliate|7. SEO|email|cross_brand|)\\&quot;' />
                  </funcallExp>
                  <literalExp charset='0' class='logical-expression' collation='LROOT' datatype='string' value='&quot;Custom&quot;' />
                  <funcallExp class='logical-expression' function='REGEXP_MATCH' shape='scalar'>
                    <identifierExp class='logical-expression' identifier='[$temp0_cse]' />
                    <literalExp charset='0' class='logical-expression' collation='LEN_RUS' datatype='string' value='&quot;^(1. Summary|2. EMR Paid Media Summary|3. Cross Channel Performance|4. Channel Perfomance|5. Pathing|6. Glossary|Granular Data|)\\.&quot;' />
                  </funcallExp>
                  <literalExp charset='0' class='logical-expression' collation='LROOT' datatype='string' value='&quot;Standard&quot;' />
                  <literalExp charset='0' class='logical-expression' collation='LROOT' datatype='string' value='&quot;Internal&quot;' />
                </caseExp>
              </binding>
            </expressions>
            <projectOp class='logical-operator'>
              <expressions>
                <binding name='[$temp0_cse]'>
                  <funcallExp class='logical-expression' function='$COLLATE_REMOTE$' shape='scalar'>
                    <funcallExp class='logical-expression' function='LOWER' shape='scalar'>
                      <identifierExp class='logical-expression' identifier='[Calculation_698339484915068929]' />
                    </funcallExp>
                    <literalExp charset='0' class='logical-expression' collation='LROOT' datatype='string' value='&quot;LEN_RUS&quot;' />
                  </funcallExp>
                </binding>
              </expressions>
              <relationOp class='logical-operator' connection='[].[sqlproxy]' name='[sqlproxy]'>
                <relation type='parameterized'>
                  <parameters>
                    <parameter name='[Parameter 1]' value='-6' />
                    <parameter name='[Parameter 2]' value='&apos;https&apos;' />
                    <parameter name='[Workbook Display Tabs Parameter]' value='&apos;reporting.ovative.com&apos;' />
                  </parameters>
                  <relation name='sqlproxy' type='table' />
                </relation>
                <cols />
              </relationOp>
            </projectOp>
          </projectOp>
        </selectOp>
      </aggregateOp>
    </projectOp>
  </logical-query>
  <datasource hasconnection='false' inline='true' name='Parameters' version='18.1'>
    <aliases enabled='yes' />
    <column alias='Central Standard Time' caption='Timezone' datatype='integer' name='[Parameter 1]' param-domain-type='list' role='measure' type='quantitative' value='-6'>
      <calculation class='tableau' formula='-6' />
      <aliases>
        <alias key='-10' value='Hawaii Standard Time' />
        <alias key='-9' value='Alaska Standard Time' />
        <alias key='-8' value='Pacific Standard Time' />
        <alias key='-7' value='Pacific Daylight Time' />
        <alias key='-6' value='Central Standard Time' />
        <alias key='-5' value='Eastern Standard Time' />
        <alias key='-4' value='Puerto Rico and US Virgin Islands Time' />
        <alias key='-3' value='Canada Newfoundland Time' />
        <alias key='-1' value='Central African Time' />
        <alias key='0' value='Greenwich Mean Time' />
        <alias key='1' value='European Central Time' />
        <alias key='2' value='Eastern European Time' />
        <alias key='3' value='Eastern African Time' />
        <alias key='4' value='Near East Time' />
        <alias key='5' value='Pakistan Lahore Time' />
        <alias key='6' value='Bangladesh Standard Time' />
        <alias key='7' value='Vietnam Standard Time' />
        <alias key='8' value='China Taiwan Time' />
        <alias key='9' value='Japan Standard Time' />
        <alias key='10' value='Australia Eastern Time' />
        <alias key='11' value='Solomon Standard Time' />
        <alias key='12' value='New Zealand Standard Time' />
      </aliases>
      <desc>
        <formatted-text>
          <run>The timezone to display dates in.&#10;&#10;Note that functionally, this is simply an integer value representing the number of hours to offset from UTC, which dates in the Tableau Server Repository are stored in. This means that it will not necessarily be accurate for timezones with Daylight Savings in place.</run>
        </formatted-text>
      </desc>
    </column>
    <column caption='Tableau Server Protocol' datatype='string' name='[Parameter 2]' param-domain-type='list' role='measure' type='nominal' value='&quot;https&quot;'>
      <calculation class='tableau' formula='&quot;https&quot;' />
    </column>
    <column caption='View By' datatype='string' name='[Parameter 3]' param-domain-type='list' role='measure' type='nominal' value='&quot;Username&quot;'>
      <calculation class='tableau' formula='&quot;Username&quot;' />
    </column>
    <column caption='Date Selection' datatype='date' name='[Parameter 4]' param-domain-type='any' role='measure' type='quantitative' value='#2019-12-14#'>
      <calculation class='tableau' formula='#2019-12-14#' />
    </column>
    <column caption='Tableau Server Name' datatype='string' name='[Workbook Display Tabs Parameter]' param-domain-type='any' role='measure' type='nominal' value='&quot;reporting.ovative.com&quot;'>
      <calculation class='tableau' formula='&quot;reporting.ovative.com&quot;' />
      <desc>
        <formatted-text>
          <run>The name of the Tableau Server instance. This value is used in the hyperlink calculations.</run>
        </formatted-text>
      </desc>
    </column>
  </datasource>
</sqlproxy>
""

**Comment by mcoles** [comment]
Hey @tspring12 , what version of Tableau are you using, and what data source is giving you this error? I'll see if I can reproduce.

**Comment by tspring12** [comment]
@mcoles Currently using 2019.3.2 but I also tried connecting in 2019.1.1. 
In 2019.1 it keeps asking to Reconnect to [TS Data Source] whereas 2019.3 asks to reconnect to 'sqlproxy.0-r95cb1g98tnw15t49g20xc7ixz? and when I pres yes I get the same error and when I press no I get the error message in the original post. 
I'm using TS_Content, TS_Background_Tasks, TS_Events, and TS_Users. Same error on all of them

**Comment by mcoles** [comment]
I just opened https://raw.githubusercontent.com/tableau/community-tableau-server-insights/master/datasources/ts_content/ts_content_02.01.twb in Desktop 2019.3.3 and did not reproduce the error.

Not sure what to think the issue might be, at this point. Can you by any chance capture it on video, or do a step-by-step set of images showing everything you're doing? Something might stand out if I can follow along.

**Comment by mcoles** [comment]
closing due to lack of response
