### ISSUE TITLE
Add job creator information to TS Background Tasks

### ISSUE THREAD

**Issue by mcoles** [tableau/community-tableau-server-insights#24]
In 2019.4, a field was introduced into the backgrounder_jobs table called job_creator. This indicates who created the job, which has been a frequent request for admins wanting to know who initiated an "run now" extract refresh, and the like. This also becomes more important with the introduction of the Create Extracts in Browser feature introduced in 2019.4 as well. Note, though, that this only works for new tasks, and will not back-populate already existing tasks.

Edit: Additionally, there's a new flag in the backrounder_jobs table called ‘run_now’, which can be used to determine whether jobs were scheduled, or run on-demand.

Given that 2019.4 is almost done, and still on the 02 version set, I think we should target the 03 version set (2020.1+).

**Comment by sunithapratipati** [comment]
Can we get SQL to get the subscriptions and the job details instead of workbook. Restricted to download the worbook

**Comment by mcoles** [comment]
Hi @sunipr--I'm not quite sure what you mean, can you clarify please?

**Comment by sunipr** [comment]
Thank you, Matt got responding! I was able to view the custom sql code behind which is of great help.

**Comment by sunipr** [comment]
Hi Matt,
Using background_jobs doesn’t give adhoc refresh details. So trying to use background_tasks, arg column to get object Id to join to task and running into conversion issue of integer. Tried different options, appreciate any input.

Thanks!
