### ISSUE TITLE
Discussion: Any security concerns about opening up these data sources to all users?

### ISSUE THREAD

**Issue by thechadd** [tableau/community-tableau-server-insights#25]
Wasn't sure if I should post this here or in the developer's forum. For our deployment I'm considering using the user filters on these data sources, but I'm wondering if they are really necessary.
Things I am *not* worried about:
- who does what and when
- What reports exist, even if they don't have access
- when others' extracts are run

It would sure save me the headache of "it's not my data source, but I need to know how the extract is running" type questions.

I'm wondering if I'm missing anything that I should be concerned about. (yeah, every company is different...just spitballin' here)

Cheers,
Chadd

**Comment by mcoles** [comment]
No, if you don't care about everyone being able to see the data here, just leave the filters off. Two areas that I consider from a restriction perspective are (a) Privacy--does everyone know that everyone else can see what they're doing, and are they okay with it? and (b) It increases attack vectors for social engineering--e.g., disgruntled employee Ned sees that the Finance team regularly looks at restricted view "Transactions Over 50K"--he then leaves the company and then helps organize a spear-phishing attempt targeting the finance team, slipping in the fact that they look at that view to help decrease suspicion. Or, obtaining the server, database, and auth method for certain restricted databases. It's valuable information for those with malevolent intent.

Oppositely, by removing all user filters, you can connect to these data sources with Prep, which is pretty cool. So if you don't see a need to restrict the info in these, it's a good idea to delete the User Filter calc entirely!

**Comment by thechadd** [comment]
It's mostly item (a) that might be a concern. I'm still relatively new at this company, and I'm going to see how they generally handle these data.  I appreciate your comment; it really helped me think it through. I'll reply with what I ultimately decide.
Side note, is this the best place for this dialog? Is there a discussion section of Github that I'm not seeing? I'd hate for this to sit as a bug/feature/whatever :)

**Comment by mcoles** [comment]
Yeah, probably. For @tableau/vizalerts I have a whole Group on the Tableau forums for discussions, but we don't have that for this tool yet. So, this place is fine for right now. I labeled this as a Question to distinguish it from the other Issue types.
