### ISSUE TITLE
DS Content: Project count ignore empty projects

### ISSUE THREAD

**Issue by Querton** [tableau/community-tableau-server-insights#29]
I noticed that the Project count in the data source seems to count only project where there is content in it. This provide a biased view of the content of a site and unfortunately prevent to see proliferation of empty folders.

Would it be possible to enhance the data source to include empty projects ?

**Comment by mcoles** [comment]
Hi @Querton. Thanks for sharing your feedback. We've heard this before, so we are putting feedback here: #4
