### ISSUE TITLE
Collecting all user IDs for a specific view or project   

### ISSUE THREAD

**Issue by PhillipDenmark** [tableau/community-tableau-server-insights#34]
Hello,

Is there any way of collecting all user IDs with access to a specific view or project so that you calculate relative usage/reach on a project/view?

I am sorry if I have placed this request in the wrong section.

KR, Phillip

**Comment by mcoles** [comment]
No, not at the moment. The closest you can get is determining who is actively _using_ a view, or content within a project using TS Events. The only way to calculate who has _access_, is by resolving all permissions granted to specific users, and then all permissions assigned via group membership. Doing this creates billions of rows and kills performance. https://github.com/tableau/community-tableau-server-insights/issues/6 was created to track progress on this issue--but after hacking away at it for quite some time, I'm not super optimistic it can be done.
