### ISSUE TITLE
TS Content Missing Fields Dimension for Dashboards/Stories

### ISSUE THREAD

**Issue by plevos** [tableau/community-tableau-server-insights#46]
Digging into the TS Content source and it appears that the only views with fields are those that were published as sheets to server. Is it possible to pull in all fields that were published on dashboards and stories?

**Comment by mcoles** [comment]
Unfortunately that data doesn't exist in the repository database for those sheet types. However, you could obtain that information from the [Metadata API](https://help.tableau.com/current/api/metadata_api/en-us/index.html), if you needed it badly enough.
