### ISSUE TITLE
Join other files to TS sources

### ISSUE THREAD

**Issue by ChristophGmeiner** [tableau/community-tableau-server-insights#49]
Hello everybody,

is there a way to join e.g. the TS Events data source with some other Google sheet?

thanks and best regards

Christoph

**Comment by mcoles** [comment]
Yes, you would need to edit the connection itself and do a cross-database join, most likely to the historical_events table. Another option would be to use Prep to connect to the published data source and join your spreadsheet to it in a flow, and output the result to a new data source. Third option is the worst; you could use Tableau's data blending feature.

**Comment by ChristophGmeiner** [comment]
Great. Thanks. The Prep way Workshop perfectly.

**Comment by mcoles** [comment]
One thing I forgot to mention for anyone else trying the Prep approach--at this time, Prep can't connect to a published data source that uses a user filter in any way, shape, or form. So before you can do so, you'll have to remove the User Filter field and any other reference to either of the USERNAME() or ISMEMBEROF() functions.
