### ISSUE TITLE
Consolidate all datasource in one workbook

### ISSUE THREAD

**Issue by KathyShen** [tableau/community-tableau-server-insights#50]
How could I consolidate all TS datasources into one single workbook? 

Because I will build a few customized admin dashboards based on TS content, TS event and TS web request etc. I want to embed the data model in the workbook itself, rather than to connect to separately published data sources. It seems very troublesome to replicate each TS data source. Is there any easier way to combine them into one single workbook?

**Comment by thechadd** [comment]
What roadblocks are you facing by connecting to them as separately published data sources?

**Comment by KathyShen** [comment]
> What roadblocks are you facing by connecting to them as separately published data sources?

I could technically connect to separately published data sources. But I don't want to have separately published data sources. Instead, I want all the data models to embed in the workbook itself. My question is, is there a way to combine all the TS data models into one workbook?

**Comment by thechadd** [comment]
I don't understand what this would resolve, but unfortunately your only option to recreate the ds's in the workbook manually.

**Comment by Scheballs** [comment]
@KathyShen Have you tried to related the individual data sources source code as seperate logical tables using the new relationships data model in the data source window?
