### ISSUE TITLE
QoL on this repo to newer versions of Tableau

### ISSUE THREAD

**Issue by arendon1** [tableau/community-tableau-server-insights#52]
More than a bug I was wondering if this awesome source is getting an update to support newer versions of Tableau Server up until 2021.1.

Thanks in advance for taking the time to respond to this.

**Comment by mcoles** [comment]
Started on the new version last week. :) No promises on when they'll be released, but hopefully within a couple weeks. I'm trying to close as many open Issues as possible...

**Comment by arendon1** [comment]
This is amazing news, thank you Matt.

**Comment by mcoles** [comment]
03.01 now released, compatible with 2020.4+
