### ISSUE TITLE
Incorporate new "Access Authoring View" event into added in 2021.1 

### ISSUE THREAD

**Issue by mcoles** [tableau/community-tableau-server-insights#59]
2021.1 added a new event type in historical_events, "Access Authoring View". This represents when a user enters Web Edit mode for an _existing_ view, or against a published data source and also then _saves_ their visualization as a view in a new workbook. Authoring a new workbook against a published data source, and then abandoning it, does not generate this event type.

Now that this event is tracked, it will be incorporated into TS Users activity aggregates, and as an "Access" event in TS Content. This should be implemented in a backward-compatible way to prior versions, which relied on the http_requests table, which by default contains only a week's worth of data as opposed to the half-year worth of data that historical_events contains.

**Comment by thechadd** [comment]
This is great in helping us one step closer to full visibility in all Explorer actions (versus viewer).  We are struggling to find a way to find Explorers who aren't using Explorer functionality such that we can demote to them to viewers.

**Comment by mcoles** [comment]
- Right?? I'm super excited about this getting added as well, especially alongside #60 . I'm incorporating both these new event types into the TS Users activity aggregate measures to support the very use case you mention.
