### ISSUE TITLE
Size is Sometimes Incorrect on TS Content

### ISSUE THREAD

**Issue by PatrickGMI** [tableau/community-tableau-server-insights#66]
I am using TS Content to analyze large disk footprints.  I am using (Folder) Item\ (Measure) Size (MB).  The number reported doesn't always appear to match reality.  Sometimes the number reported by TS Content is much higher than the size of a data source when downloaded from the server to my local hard drive.  

At first, I thought that it might be due to versioning:  multiple historical copies of the item stored on the server.  However, even after deleting all of history, or checking a newly published extract, the size was still not matching.

What is the size field measuring for TS Content Items?  I can't seem to figure out how it correlates to actual file sizes.  This is against v2.02 of TS Content, and v2021.1 of Tableau Server.

**Comment by mcoles** [comment]
Are you looking at the size of a .twbx / tdsx? Those are compressed. You
could try extracting the .hyper file and comparing that size to what TS
Content says.

**Comment by PatrickGMI** [comment]
Matt,
Thank you.  Yes, the size field is very close to matching when I compare the unzipped size.  (One test showed ~0.3 MB higher on disk this time compared to the TS Content field.  Still this is vastly closer than any other comparison we have tried.)
Thanks!
Patrick
