### ISSUE TITLE
Question: How do I use Tableau Server Insights To Show View Access Counts for Items that use Oracle DB Connectors?

### ISSUE THREAD

**Issue by PatrickGMI** [tableau/community-tableau-server-insights#69]
How would I use TSI to show View Access Counts for workbooks that utilize Oracle data sources?

In the GUI I would Explore --> All Data Sources --> Filter to All (Published & Embedded) --> Filter to Connection Type Oracle, and then I would laboriously go through each item found, opening the DS in a new tab, looking at all connected workbooks, then for each workbook look at the views and their access counts.

Obviously this is too much work to do at scale.  How do I use Tableau Server Insights to show me how well utilized are views that might contain oracle data (because the workbook uses the data source)?

So far:  I have a view that shows me all workbooks and their views, and those view access counts (TS Content).  I have a second view (TS Data Connections) that shows me all data connections that contain oracle connections.  If the datasource is embedded, I can blend these two.  But I can't find a way to link published oracle data sources to workbooks.  Nor, how I would make one comprehensive analysis irrespective of published vs embedded.  Any suggestions would be appreciated.

Thanks!
Patrick

**Comment by beduke17** [comment]
I typically do the blend here too if you need a simple view to see if anything was accessed or not. You should be able to blend on the datasourceID and ownerID, and filter on the DbClass.

**Comment by mcoles** [comment]
Yeah, you'd have to (a) blend or (b) use Prep or (c) integrate the view stats SQL from TS Content into TS Data Connections. My preferred option if you don't need it updating super frequently would be (b) as it'd be fairly simple to do and would perform well.

Keep in mind that TS Data Connections cannot map a view to a connection, only workbooks. So the question you'd really be answering with this approach is "what are the access statistics for the workbooks with an Oracle connection _anywhere inside them_, regardless of whether or not the view accessed actually uses an Oracle connection?". To get finer grained and do the proper linking, you have to go deeper into PostgreSQL or, more properly (but also more confusingly) into the Metadata API.
