### ISSUE TITLE
Tableau relative date filter apply button

### ISSUE THREAD

**Issue by nuriiiiiii** [tableau/community-tableau-server-insights#70]
Is it possible to create an "Apply button" for relative date filter?
It takes a lot of time if I change time option (ex. from year to month).
I unchecked "Auto Update Dashboard", but it is only possible in Tableau file.
I want to use apply button on the published dashboard.
Please tell me how if possible.

**Comment by thechadd** [comment]
Hi, this is the Tableau Server Insights project for creating data sources based on Tableau Server's internal database. For help with Tableau, please reach out to the Tableau Community: https://www.tableau.com/community

**Comment by yurifal** [comment]
> I unchecked "Auto Update Dashboard", but it is only possible in Tableau file.

You can do it when viewing a dash on Tableau Server / Online (Cloud) / Public:
<img width="341" alt="Screenshot 2022-08-08 at 14 22 15" src="https://user-images.githubusercontent.com/2496788/183429263-1697caee-938f-4c61-a213-ae6491581820.png">

**Comment by beduke17** [comment]
I typically have a parameter for multiple filters to apply or a setup dashboard to prefilter items just like in https://kb.tableau.com/articles/howto/creating-an-apply-button-for-multiple-filters-on-a-dashboard

A single date has the option to have an [apply button ](https://help.tableau.com/current/pro/desktop/en-us/filtering.htm)though:

> Show Apply Button - toggles whether to show the Apply button at the bottom of the filter. When shown, changes to the filter are only applied after you click the button. Pending changes are indicated with a green color. This option is only available in multiple values lists and dropdowns. This options is available in web authoring.
