### ISSUE TITLE
Slack data dev channel

### ISSUE THREAD

**Issue by rickymedrano** [tableau/community-tableau-server-insights#71]
Hi, 
The link in the readme to join the Slack Data Dev channel https://github.com/tableau/community-tableau-server-insights is only if you're already apart of the community. Can you post a link where I can sign up to join the channel?

**Comment by mcoles** [comment]
Try https://tabsoft.co/JoinTableauDev

**Comment by rickymedrano** [comment]
Get a The Link is No Longer Active unfortunately.

**Comment by ken-durk** [comment]
it sure would be nice to get into that slack group

**Comment by mcoles** [comment]
I'm asking around...

**Comment by mcoles** [comment]
The answer is that you have to join the developer program to get access to the Slack channel. So go here: https://www.tableau.com/developer , sign up, and then you should be able to access https://tableau-datadev.slack.com/ .

**Comment by rickymedrano** [comment]
They've updated the link, this is working now http://tabsoft.co/https://join.slack.com/t/tableau-datadev/shared_invite/zt-1fw6x1utj-f7tjxvFL0Lfa883H54fPCg
