### ISSUE TITLE
Source for Tableau Server Web Views Count

### ISSUE THREAD

**Issue by bparkin1283** [tableau/community-tableau-server-insights#75]
![image](https://user-images.githubusercontent.com/22919479/211429354-5781afb0-fde6-4c09-a158-cac984ac2ac2.png)

Does anyone know the data source and/or logic for the UI "Views" statistics? I'm trying to wrap my head around it because http_requests retention is only on the order of days and TS Events (historical_events) on the order of weeks (26).

views_stats stores the cumulative view counts, but only stores "last accessed", so I don't know how it could be used to do the logic on the UI binning (1-month... 12-month, all-time ...), so something is keeping track of access timestamps up to 12 months.  

Any thoughts on where this data is coming from and being stored? Thanks.

**Comment by mcoles** [comment]
These come from the *_metrics_aggregations tables. I don't reference them in the data sources in this project because there are some reasons they don't always jibe with what is in historical_events, and I preferred consistency with that table as a source of truth.

**Comment by bparkin1283** [comment]
Thanks, Matt. This should get me started. It would make sense that the front-end uses stored procs in the workgroup db that utilize these *_metrics_aggregations tables, which we could then "borrow". I'll take a look. Appreciate the response. Take care.
