### ISSUE TITLE
Add flows input and output information

### ISSUE THREAD

**Issue by omargherardi** [tableau/community-tableau-server-insights#79]
Hi,

I was directed here because I needed to map all tableau server, its content and connections between objects, flows, datasources and sql server's tables. It is easy to connect views with workbook - and easier thanks to your work. It is also easy to map relations between published datasources and sql server's tables. But the thing I struggle doing is to map all relations (input/output) with flows. raw data seems to be incomplete (no table name, for example), but we know tableau has all information, because in the server, if we enter in a view, we can see all flows related to that view, and back to all tables, dbs and servers. 

Maybe could be useful to add flow connection in a separate workbook.

Anyway, I also accept hints on how to do this (infamous) job

Thanks,

Omar

**Comment by mcoles** [comment]
The short answer here is that I tried to [model flow inputs/outputs in TS Data Connections](https://github.com/tableau/community-tableau-server-insights/issues/40), but could not find a satisfactory way to do it.

But at a higher level, the dependency relationships you are after are really not designed to be consumed from the Tableau Server postgreSQL repository database. The data you want is stored in the [Metadata API](https://help.tableau.com/current/api/metadata_api/en-us/index.html), which uses a GraphQL model to store information in. It has what you need and more, capturing even column-level mapping details. So my recommendation would be to use that as your resource instead.
